services:
  - type: web
    name: telegram-pixabay-bot
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: BOT_TOKEN
        value: 8071576925:AAGgx_Jkuu-mRpjdMKiOQCDkkVQskXQYhQo
      - key: ADMIN_ID
        value: 7251748706
      - key: PIXABAY_API_KEY
        value: 51444506-bffefcaf12816bd85a20222d1
    healthCheckPath: /health
    numInstances: 1
    plan: free
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1
